[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustix = "0.38.31"
rustix-openpty = "0.1.1"
termios = "0.3.3"
winit = "0.29.10"
